version: '3'

services:
    database:
        image: mysql:8
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'symfony4_react_crm'
            MYSQL_USER: 'dbuser'
            MYSQL_PASSWORD: 'dbpassword'
